export const types = {
  LOAD_PROJECTS: 'UI_LOAD_PROJECTS',
  SET_PROJECTS_ERROR: 'UI_SET_PROJECTS_ERROR',
  SET_PROJECTS_LOADING: 'UI_SET_PROJECTS_LOADING',
  SET_PROJECT_CACHE: 'UI_SET_PROJECT_CACHE',
  SET_PROJECT_VIEW_PREFS: 'UI_SET_PROJECT_VIEW_PREFS',
  SET_PROJECTS: 'UI_SET_PROJECTS',
  SET_LIVE_STATS: 'UI_SET_LIVE_STATS',
  SET_LIVE_STATS_PROJECT: 'UI_SET_LIVE_STATS_PROJECT',
}
